# Generated by Django 3.2.6 on 2021-08-08 07:38

from django.db import migrations
from phones.management.commands.import_phones import Command


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210808_1432'),
    ]

    com = Command()
    operations = [
        migrations.RunPython(com.handle()),
    ]
